### ISSUE TITLE
Unable to enter the game, bad inventory data?

### ISSUE THREAD

**Issue by DumbJoe** [sajonoso/d2mods#2]
Doesn't seem to work on a current save file but works if I create a brand new character save.....

Also on that note, Hero Editor complains about unknown amulets/rings when loading a character up on there, so either you overlooked a typo or Hero Editor hasn't quite been fully updated for up to 1.14D changes....

Screenshots provided:
![a](https://i.imgur.com/VycQNvG.png)
![b](https://i.imgur.com/ZQCEvUB.png)

**Comment by DumbJoe** [comment]
OK so some of your mos work, like the 10x10 stash and 10x8 cube inventory, the font fix and the full merc still gives me that error. The others I don't bother to try as I have no use for them.

**Comment by DumbJoe** [comment]
There's another mod on reddit I saw that gives you an extra two rows of private inventory space on your character, can you add that in to this collection too? Along with the other two mods I mentioned in another issue?

**Comment by sajonoso** [comment]
Hi @DumbJoe , thanks for the feedback.  I will do some testing on what causes the bad data when time permits.  This may take  6 months or longer as this is just a hobby for me (my day job keeps me busy).  I have looked at increasing the private inventory space before, but I don't like how it will involve squashing the layout like this:
https://thumbs.gfycat.com/EllipticalGrouchyJumpingbean-mobile.jpg

If I can find the .dc6 file for the extra two rows like this layout:
https://media.moddb.com/cache/images/mods/1/28/27519/thumb_620x2000/Screenshot041.jpg
, then I will consider creating a mod for this request

**Comment by DumbJoe** [comment]
oh wow that's some serious efficient use of space on that first screenshot! hahaha But yeah, it does kinda look out of place....maybe instead of efficient space use, you do the two extra rows of space but then add tabs for multiple pages? So effectively using the same or more amount of space....that wasy there would less need to keep portalling back everytime your cube or and inventory fills up because you're such a hoarder...hahaha

Like this guy's?
![p](http://i.imgur.com/s9QSsLX.jpg)

Link: https://www.reddit.com/r/diablo2/comments/518gid/i_have_working_stash_size_mod_files_for_114/

**Comment by sajonoso** [comment]
Hi @DumbJoe, the mod to increase inventory space has now been added.  I have also added notes to mods that may potentially cause the bad data.

**Comment by DumbJoe** [comment]
Oh you haven't figured out why it happens?
