### ISSUE TITLE
Item randomizer

### ISSUE THREAD

**Issue by ChristianPyth** [sajonoso/d2mods#3]
Add item randomizer :) (stats of item, how many of them etc.)

**Comment by sajonoso** [comment]
@ChristianPyth, some new Horadric cube recipes have been added to try achieve this.  The item you put in will be converted to a random rare item.  The recipes are:

1 weapon + 1 identify Scroll + 1 thawing potion -> rare weapon of same type
1 armour + 1 identify Scroll + 1 thawing potion -> rare armour of same type (also works on rings and amulets)

Note, if the items are ethereal they will become normal.  If they are socketed and have gems, the gems will be lost and they may become unsocketed.

**Comment by ChristianPyth** [comment]
Thanks, now it makes more fun :)
